find_path(xraylib_INCLUDE_DIR xraylib.mod ${CMAKE_MODULE_PATH}/include)

message(VERBOSE "Looking in ${xraylib_SRCDIR} ${CMAKE_MODULE_PATH} for xraylib library .a or .so (LINUX) or .dylib (APPLE)")

find_library(xraylib1_LIBRARY xrl PATHS ${xraylib_SRCDIR} ${CMAKE_MODULE_PATH}/lib)
find_library(xraylib2_f03_LIBRARY xrlf03 PATHS ${xraylib_SRCDIR} ${CMAKE_MODULE_PATH}/lib)

if(xraylib_INCLUDE_DIR)
  message (VERBOSE "found xraylib.h - so now have a valid include dir")
endif()
if(xraylib1_LIBRARY)
  message (VERBOSE "found xraylib - so now have a valid library - ${xraylib1_LIBRARY}")
endif()
if(xraylib2_f03_LIBRARY)
  message (VERBOSE "found xraylibf - so now have a valid library - ${xraylib2_f03_LIBRARY}")
endif()

if(DEFINED xraylib_INCLUDE_DIR AND (DEFINED xraylib1_LIBRARY OR DEFINED xraylib2_f03_LIBRARY))
#if(xraylib_INCLUDE_DIR)
  set(XRAYLIB_FOUND "TRUE" PARENT_SCOPE)
  set(XRAYLIB_FOUND TRUE)
  message(STATUS "All is good with xraylib - continuing - ${XRAYLIB_FOUND}")
else()
  message(STATUS "Issues - missing something in xraylib - this may cause trouble ahead")
endif()

if(XRAYLIB_FOUND)
  set(xraylib_LIBRARIES ${xraylib1_LIBRARY} ${xraylib2_f03_LIBRARY})
  set(xraylib_LIBRARIES ${xraylib1_LIBRARY} ${xraylib2_f03_LIBRARY} PARENT_SCOPE)
  set(xraylib_INCLUDE_DIRS ${xraylib_INCLUDE_DIR} PARENT_SCOPE)
endif()
