
#do not expect a lapack95 header file
find_path(lapack95_INCLUDE_DIR NAMES f95_lapack.mod ${CMAKE_MODULE_PATH}/include/lapack95)
#find_library(lapack95_LIBRARY lapack95)
#find_path(lapack95_INCLUDE_DIR lapack95.h)
#find_library(lapack95_LIBRARY lapack95)
message(STATUS "Looking in ${lapack95_SRCDIR} ${CMAKE_MODULE_PATH} for lapack95 library .a or .so")
#find_library(lapack95_LIBRARY ${lapack95_SRCDIR} lapack95)
find_library(lapack_LIBRARY lapack PATHS ${lapack95_SRCDIR} ${CMAKE_MODULE_PATH}/lib)
find_library(lapack95_LIBRARY lapack95 PATHS ${lapack95_SRCDIR} ${CMAKE_MODULE_PATH}/lib)
#find_library(lapack95_LIBRARY lapack95 PATHS ${lapack95_SRCDIR} ${CMAKE_MODULE_PATH}/lib)


#mymessage(4 STATUS "JSL - Value is ${lapack95_INCLUDE_DIR}")
if(lapack95_INCLUDE_DIR)
  message (STATUS "found lapack95.mod - so now have a valid include dir")
endif()
      
if(DEFINED lapack95_LIBRARY)
  message (STATUS "found lapack95.so or .a -  - so now have a valid library")
  list(APPEND lapack95_LIBRARY ${lapack_LIBRARY})
#  message (STATUS "VALUE IS NOW -${lapack95_LIBRARY} -${lapack_LIBRARY}")
  # note, if we did not find the lapack95_INCLUDE_DIR, but did find, the lapack95_LIBRARY, let's check one level up
  if (NOT lapack95_INCLUDE_DIR)
#    set(UP_ONE_LEVEL ${lapack95_LIBRARY}
    get_filename_component(PARENT_DIR ${lapack95_LIBRARY} PATH)
    get_filename_component(PARENT_PARENT_DIR ${PARENT_DIR} PATH)
    message (STATUS "Looking for lapack95.mod or f95_lapack.mod in ${PARENT_PARENT_DIR}")
    find_path(lapack95_INCLUDE_DIR NAMES lapack95.mod f95_lapack.mod PATH ${PARENT_PARENT_DIR} PATH_SUFFIXES modules lib include)
    message(STATUS "MYVALUE is ${lapack95_INCLUDE_DIR}")
    if(lapack95_INCLUDE_DIR})
      message (STATUS "found lapack95.mod or f95_lapack.mod - so now have a valid include dir - ${lapack95_INCLUDE_DIR}")
    endif()
  endif()
endif()

#if(lapack95_INCLUDE_DIR AND lapack95_LIBRARY)
if(DEFINED lapack95_LIBRARY)
  set(LAPACK95_FOUND TRUE)
  set(LAPACK95_FOUND TRUE PARENT_SCOPE)
  set(LAPACK95_LIBRARY ${lapack95_LIBRARY})
  set(LAPACK95_LIBRARY ${lapack95_LIBRARY} PARENT_SCOPE)
  set(LAPACK95_LIBRARIES ${lapack95_LIBRARY})
  set(LAPACK95_LIBRARIES ${lapack95_LIBRARY} PARENT_SCOPE)
  set(LAPACK95_INCLUDE_DIR ${lapack95_INCLUDE_DIR})
  set(LAPACK95_INCLUDE_DIR ${lapack95_INCLUDE_DIR} PARENT_SCOPE)
  set(lapack95_LIBRARY ${lapack95_LIBRARY})
  set(lapack95_LIBRARY ${lapack95_LIBRARY} PARENT_SCOPE)
  set(lapack95_LIBRARIES ${lapack95_LIBRARY})
  set(lapack95_LIBRARIES ${lapack95_LIBRARY} PARENT_SCOPE)
  set(lapack95_INCLUDE_DIR ${lapack95_INCLUDE_DIR})
  set(lapack95_INCLUDE_DIR ${lapack95_INCLUDE_DIR} PARENT_SCOPE)

  message(STATUS "All is good for package lapack95 - continuing - library - ${LAPACK95_LIBRARY} - cflags - ${LAPACK95_INCLUDE_DIR}")
else()
  message(STATUS "Issues - missing something in lapack95 - trouble ahead")
endif()

if(LAPACK_FOUND)
#  set(lapack95_LIBRARIES ${lapack95_LIBRARY})
  set(lapack95_INCLUDE_DIRS ${lapack95_INCLUDE_DIR} PARENT_SCOPE)
  
endif()
