
#do not expect a lapack95 header file
find_path(lapack95_INCLUDE_DIR lapack95.h ${CMAKE_MODULE_PATH}/include/lapack95)
#find_library(lapack95_LIBRARY lapack95)
#find_path(lapack95_INCLUDE_DIR lapack95.h)
#find_library(lapack95_LIBRARY lapack95)
mymessage(2 STATUS "Looking in ${lapack95_SRCDIR} ${CMAKE_MODULE_PATH} for lapack95 library .a or .so")
#find_library(lapack95_LIBRARY ${lapack95_SRCDIR} lapack95)
find_library(lapack95_LIBRARY liblapack95.so ${lapack95_SRCDIR} ${CMAKE_MODULE_PATH}/lib)

#if(lapack95_INCLUDE_DIR)
#	message (STATUS "found lapack95.h - so now have a valid include dir")
#endif()
if(lapack95_LIBRARY)
	mymessage (2 STATUS "found lapack95.so or .a -  - so now have a valid library")
endif()

#if(lapack95_INCLUDE_DIR AND lapack95_LIBRARY)
if(lapack95_LIBRARY)
  set(LAPACK95_FOUND TRUE)
  set(LAPACK95_FOUND TRUE PARENT_SCOPE)
  mymessage(2 STATUS "All is good for package lapack95 - continuing")
else()
  mymessage(1 STATUS "Issues - missing something in lapack95 - trouble ahead")
endif()

if(LAPACK_FOUND)
#  set(lapack95_LIBRARIES ${lapack95_LIBRARY})
  set(lapack95_INCLUDE_DIRS ${lapack95_INCLUDE_DIR} PARENT_SCOPE)
endif()
