find_path(openmpi_INCLUDE_DIR openmpi.h ${CMAKE_MODULE_PATH}/include/openmpi)
mymessage(3 STATUS "Looking in ${openmpi_SRCDIR} ${CMAKE_MODULE_PATH} for openmpi library .a or .so")
find_library(openmpi_LIBRARY libopenmpi.so ${openmpi_SRCDIR} ${CMAKE_MODULE_PATH}/lib)

if(openmpi_INCLUDE_DIR)
  mymessage(3 STATUS "found openmpi.h - so now have a valid include dir")
endif()
if(openmpi_LIBRARY)
  mymessage(3 STATUS "found openmpi.so or .a -  - so now have a valid library")
endif()

if(openmpi_INCLUDE_DIR AND openmpi_LIBRARY)
  set(openmpi_FOUND TRUE)
  set(openmpi_FOUND TRUE PARENT_SCOPE)
  mymessage(3 STATUS "All is good for openmpi - continuing")
else()
  mymessage(1 STATUS "Issues - missing something for openmpi - trouble ahead")
endif()

if(openmpi_FOUND)
  set(openmpi_LIBRARIES ${openmpi_LIBRARY})
  set(openmpi_INCLUDE_DIRS ${openmpi_INCLUDE_DIR})
endif()
