find_path(plplot_INCLUDE_DIR plplot.h ${CMAKE_MODULE_PATH}/include/plplot)
mymessage(2 STATUS "Looking in ${plplot_SRCDIR} ${CMAKE_MODULE_PATH} for plplot library .a or .so")

find_library(plplot_LIBRARY libplplot.so ${plplot_SRCDIR} ${CMAKE_MODULE_PATH}/lib)

if(plplot_INCLUDE_DIR)
  mymessage (3 STATUS "found plplot.h - so now have a valid include dir")
endif()
if(plplot_LIBRARY)
  mymessage (3 STATUS "found plplot.so or .a -  - so now have a valid library")
endif()

if(plplot_INCLUDE_DIR AND plplot_LIBRARY)
  set(PLPLOT_FOUND TRUE)
  set(PLPLOT_FOUND TRUE PARENT_SCOPE)
  mymessage(4 STATUS "All is good for plplot - continuing")
else()
  mymessage(3 STATUS "Issues - missing something with plplot - possible trouble ahead if this is not first build or expected to find it")
endif()

if(PLPLOT_FOUND)
  set(plplot_LIBRARIES ${plplot_LIBRARY})
  set(plplot_INCLUDE_DIRS ${plplot_INCLUDE_DIR} PARENT_SCOPE)
  set(plplot_LIBRARIES ${plplot_LIBRARY} PARENT_SCOPE)
  set(plplot_INCLUDE_DIRS ${plplot_INCLUDE_DIR})
endif()
